version: 1.1.1.{build}
os: Windows Server 2012



#init:
#  - ps: iex ((New-Object Net.WebClient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
#on_finish:
#  - ps: $blockRdp = $true; iex ((New-Object Net.WebClient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))


  
install:
  - cmd: MKDIR tmp
  - cmd: CD tmp
  - ps: Start-FileDownload 'https://github.com/loresoft/msbuildtasks/releases/download/1.5.0.196/MSBuild.Community.Tasks.v1.5.0.196.msi'
  - cmd: msiexec.exe /qn /norestart /i MSBuild.Community.Tasks.v1.5.0.196.msi ALLUSERS=1 ADDLOCAL=MSBuildTasksFeature /l*v "install-msbuildtasks.log"
  - ps: Start-FileDownload 'https://github.com/OpenCover/opencover/releases/download/4.6.519/opencover.4.6.519.msi'
  - cmd: msiexec.exe /qn /norestart /i opencover.4.6.519.msi ALLUSERS=1 /l*v "install-opencover.log"
  - cmd: CD ..
  - cmd: FOR /F "tokens=1,2*" %%i in ('REG QUERY HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\MSBuild\ToolsVersions\14.0 /V MSBuildToolsPath') DO IF "%%i"=="MSBuildToolsPath" SET "PATH=%%k;%PATH%"
cache:
  - packages -> **\packages.config



build:
  project: GeoSik.proj
  parallel: true
  verbosity: minimal
build_script:
  - cmd: msbuild.exe GeoSik.proj /nologo /t:UpdateVersion;Release /p:GenerateDocumentation="False" /m /l:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /v:m /fl /flp:logfile=tmp\build.log;verbosity=diagnostic;encoding=UTF-8 /nr:False
platform: Any CPU
configuration: Release
before_build:
  - cmd: SET CCNetLabel=%APPVEYOR_BUILD_VERSION%
  - cmd: CD .nuget
  - cmd: NuGet.exe restore "packages.config" -PackagesDirectory ..\packages
  - cmd: NuGet.exe restore "..\doc\packages.config" -PackagesDirectory ..\packages
  - cmd: CD ..
  - cmd: FOR /F %%i IN ('DIR .\packages\EWSoftware.SHFB.* /AD /B') DO SET SHFBROOT=%APPVEYOR_BUILD_FOLDER%\packages\%%i\Tools\



test_script:
  - ps: (Resolve-Path tmp\*.xunit-results.xml) | ForEach-Object { (New-Object Net.WebClient).UploadFile("https://ci.appveyor.com/api/testresults/xunit/$($env:APPVEYOR_JOB_ID)", $_) }



artifacts:
  - path: tmp\out\bin\*.nupkg
    type: NuGet
  - path: tmp\out\bin\*.zip



deploy:
  - provider: NuGet
    server: https://www.myget.org/F/isogeo/api/v2/package
    api_key:
      secure: Iu8h9DYVcJWywLWAQowayV8lQzzU31p9SPyrTY7ItGxbciykN9Wy2AxuU3FE0RXT
    artifact: /.*\.nupkg/
    skip_symbols: true
    on:
      branch: master
  - provider: NuGet
    api_key:
      secure: 6qsDT4uV1HnaEVNi4hV2R9qG12o3ZVXgoZjGgxDvImFhm6d11CUTqoSXxfZ/3uAN
    artifact: /.*\.nupkg/
    skip_symbols: true
    on:
      branch: master
      appveyor_repo_tag: true
  - provider: GitHub
    auth_token:
      secure: Rlhui0x/FJviVHpu89ZGy0PnEuzqsrMpECDjoSGb2+OkKm0UixP+LtMIEDy4XX1K
    description: ''
    artifact: /.*/
    draft: true
    on:
      branch: master
      appveyor_repo_tag: true
